require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/email_addresses", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # EmailAddress. As you add validations to EmailAddress, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      EmailAddress.create! valid_attributes
      get email_addresses_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      email_address = EmailAddress.create! valid_attributes
      get email_address_url(email_address)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_email_address_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      email_address = EmailAddress.create! valid_attributes
      get edit_email_address_url(email_address)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EmailAddress" do
        expect {
          post email_addresses_url, params: { email_address: valid_attributes }
        }.to change(EmailAddress, :count).by(1)
      end

      it "redirects to the created email_address" do
        post email_addresses_url, params: { email_address: valid_attributes }
        expect(response).to redirect_to(email_address_url(EmailAddress.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EmailAddress" do
        expect {
          post email_addresses_url, params: { email_address: invalid_attributes }
        }.to change(EmailAddress, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post email_addresses_url, params: { email_address: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested email_address" do
        email_address = EmailAddress.create! valid_attributes
        patch email_address_url(email_address), params: { email_address: new_attributes }
        email_address.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the email_address" do
        email_address = EmailAddress.create! valid_attributes
        patch email_address_url(email_address), params: { email_address: new_attributes }
        email_address.reload
        expect(response).to redirect_to(email_address_url(email_address))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        email_address = EmailAddress.create! valid_attributes
        patch email_address_url(email_address), params: { email_address: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested email_address" do
      email_address = EmailAddress.create! valid_attributes
      expect {
        delete email_address_url(email_address)
      }.to change(EmailAddress, :count).by(-1)
    end

    it "redirects to the email_addresses list" do
      email_address = EmailAddress.create! valid_attributes
      delete email_address_url(email_address)
      expect(response).to redirect_to(email_addresses_url)
    end
  end
end
